from __future__ import annotations

import json
from typing import Literal

from tests.scripts.chaos.harness import Case, Context, free_port, tuple_case


def build_cases(ctx: Context) -> list[Case]:
    FIX = ctx.fixtures
    URL = ctx.url
    ART = ctx.artifacts
    BASE = ctx.base
    single = FIX / "single_turn.jsonl"
    single.write_text(json.dumps({"text": "hello", "output_length": 4}) + "\n")
    mooncake = FIX / "mooncake.jsonl"
    mooncake.write_text(
        json.dumps({"timestamp": 0, "text_input": "hello", "output_length": 4}) + "\n"
    )
    invalid_jsonl = FIX / "invalid.jsonl"
    invalid_jsonl.write_text("{not json}\n")
    random_pool = FIX / "random_pool"
    random_pool.mkdir()
    (random_pool / "prompt.txt").write_text("hello random pool\n")

    multi_turn = FIX / "multi_turn.jsonl"
    multi_turn.write_text(
        json.dumps(
            {
                "session_id": "gauntlet-session",
                "turns": [
                    {"text": "Say alpha.", "output_length": 4},
                    {"text": "Now say beta.", "output_length": 4},
                ],
            }
        )
        + "\n"
    )

    speed_root = FIX / "speed_bench"
    (speed_root / "run_coding").mkdir(parents=True)
    (speed_root / "run_coding" / "profile_export_aiperf.json").write_text(
        json.dumps(
            {
                "input_config": {
                    "models": {"items": [{"name": "mock-model"}]},
                    "datasets": [
                        {
                            "name": "main",
                            "type": "public",
                            "dataset": "speed_bench_coding",
                        }
                    ],
                },
                "output_token_throughput": {"avg": 42.0},
            }
        )
    )
    (speed_root / "run_coding" / "server_metrics_export.json").write_text(
        json.dumps(
            {
                "metrics": {
                    "sglang:spec_accept_rate": {"series": [{"stats": {"avg": 0.75}}]}
                }
            }
        )
    )

    template_config = FIX / "template_profile.yaml"
    template_config.write_text(
        "model: mock-model\n"
        "endpoint:\n"
        "  urls:\n"
        f"    - {URL}\n"
        "  type: template\n"
        "  path: /v1/custom-multimodal\n"
        "  template:\n"
        '    body: \'{{ {"model": model, "messages": [{"role": "user", "content": text}], "max_tokens": max_tokens} | tojson }}\'\n'
        "    responseField: choices.0.message.content\n"
        "dataset:\n"
        "  type: synthetic\n"
        "  entries: 1\n"
        "  prompts:\n"
        "    isl: 16\n"
        "    osl: 8\n"
        "phases:\n"
        "  type: concurrency\n"
        "  concurrency: 1\n"
        "  requests: 1\n"
        "artifacts:\n"
        f"  dir: {ART / 'profile-template-config'}\n"
        "tokenizer:\n"
        "  name: builtin\n"
        "gpuTelemetry:\n"
        "  enabled: false\n"
        "runtime:\n"
        "  ui: none\n"
    )

    base = [
        "uv",
        "run",
        "aiperf",
        "profile",
        "--model",
        "mock-model",
        "--url",
        URL,
        "--tokenizer",
        "builtin",
        "--ui",
        "none",
        "--request-timeout-seconds",
        "10",
        "--wait-for-model-timeout",
        "0",
        "--workers-max",
        "1",
        "--no-gpu-telemetry",
    ]

    def _merge(base_cmd: list[str], extras: list[str]) -> list[str]:
        extra_flags = {tok for tok in extras if tok.startswith("--")}
        out: list[str] = []
        skip_next = False
        for idx, tok in enumerate(base_cmd):
            if skip_next:
                skip_next = False
                continue
            if tok in extra_flags:
                if idx + 1 < len(base_cmd) and not base_cmd[idx + 1].startswith("--"):
                    skip_next = True
                continue
            out.append(tok)
        return out + list(extras)

    def prof(
        name: str, *args: str, timeout: int = 90
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        return (
            name,
            _merge(base, ["--artifact-dir", str(ART / name), *args]),
            timeout,
            "fail",
        )

    def prof_pass(
        name: str, *args: str, timeout: int = 120
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        return (
            name,
            _merge(base, ["--artifact-dir", str(ART / name), *args]),
            timeout,
            "pass",
        )

    def prof_gpu_pass(
        name: str, *args: str, timeout: int = 120
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        cmd = [arg for arg in base if arg != "--no-gpu-telemetry"]
        return (
            name,
            _merge(cmd, ["--artifact-dir", str(ART / name), *args]),
            timeout,
            "pass",
        )

    def config_pass(
        name: str, *args: str, timeout: int = 60
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        cmd = [
            "uv",
            "run",
            "aiperf",
            "config",
            "generate",
            "--model",
            "mock-model",
            "--url",
            URL,
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--tokenizer",
            "builtin",
            "--ui",
            "none",
        ]
        return name, cmd + list(args), timeout, "pass"

    def cmd_pass(
        name: str, cmd: list[str], timeout: int = 60
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        return name, cmd, timeout, "pass"

    def profile_full(
        name: str,
        *extra: str,
        request_count: str | None = "2",
        concurrency: str | None = "1",
        urls: list[str] | None = None,
        tokenizer: bool = True,
        gpu_disabled: bool = True,
        server_metrics_disabled: bool = False,
        timeout: int = 180,
    ) -> tuple[str, list[str], int, Literal["pass", "fail"]]:
        cmd = ["uv", "run", "aiperf", "profile", "--model", "mock-model"]
        for url in urls or [URL]:
            cmd += ["--url", url]
        if request_count is not None:
            cmd += ["--request-count", request_count]
        if concurrency is not None:
            cmd += ["--concurrency", concurrency]
        if tokenizer:
            cmd += ["--tokenizer", "builtin"]
        cmd += [
            "--ui",
            "none",
            "--request-timeout-seconds",
            "30",
            "--wait-for-model-timeout",
            "0",
            "--workers-max",
            "1",
            "--artifact-dir",
            str(ART / name),
        ]
        if gpu_disabled:
            cmd += ["--no-gpu-telemetry"]
        if server_metrics_disabled:
            cmd += ["--no-server-metrics"]
        return name, _merge(cmd, list(extra)), timeout, "pass"

    cases: list[tuple[str, list[str], int, Literal["pass", "fail"]]] = [
        # Mutually exclusive / duplicate CLI forms should fail at parse or config validation.
        prof(
            "fixed-auto-and-start-offset",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(mooncake),
            "--custom-dataset-type",
            "mooncake-trace",
            "--fixed-schedule",
            "--fixed-schedule-auto-offset",
            "--fixed-schedule-start-offset",
            "0",
        ),
        prof(
            "fixed-end-before-start",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(mooncake),
            "--custom-dataset-type",
            "mooncake-trace",
            "--fixed-schedule",
            "--fixed-schedule-start-offset",
            "100",
            "--fixed-schedule-end-offset",
            "0",
        ),
        prof(
            "public-and-custom-dataset",
            "--endpoint-type",
            "chat",
            "--public-dataset",
            "sharegpt",
            "--input-file",
            str(single),
            "--custom-dataset-type",
            "single-turn",
        ),
        prof(
            "custom-type-without-input-file",
            "--endpoint-type",
            "chat",
            "--custom-dataset-type",
            "single-turn",
        ),
        prof_pass(
            "input-file-without-custom-type",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(single),
        ),
        # `aiperf config generate` was retired; the surviving config commands
        # are init / expand / validate. Verify the retired verb fails cleanly.
        (
            "config-generate-gpu-telemetry-tokens",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "generate",
                "--model",
                "mock-model",
                "--url",
                URL,
                "--endpoint-type",
                "chat",
                "--request-count",
                "1",
                "--tokenizer",
                "builtin",
                "--ui",
                "none",
                "--gpu-telemetry",
                "pynvml",
                "dashboard",
                "--format",
                "json",
            ],
            60,
            "fail",
        ),
        prof_pass(
            "ready-check-mode-interval",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--wait-for-model-timeout",
            "5",
            "--wait-for-model-mode",
            "both",
            "--wait-for-model-interval",
            "1",
        ),
        prof(
            "bad-jsonl-single-turn",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(invalid_jsonl),
            "--custom-dataset-type",
            "single-turn",
        ),
        prof(
            "nontext-tokenizer-on-image-retrieval",
            "--endpoint-type",
            "image-retrieval",
            "--tokenizer",
            "builtin",
            "--image-batch-size",
            "1",
        ),
        prof_pass(
            "streaming-embeddings",
            "--endpoint-type",
            "embeddings",
            "--streaming",
            "--batch-size",
            "2",
        ),
        prof_pass(
            "streaming-rankings",
            "--endpoint-type",
            "nim-rankings",
            "--streaming",
            "--rankings-passages-mean",
            "2",
        ),
        prof_pass(
            "server-token-count-embeddings",
            "--endpoint-type",
            "embeddings",
            "--use-server-token-count",
        ),
        prof(
            "negative-request-count",
            "--endpoint-type",
            "chat",
            "--request-count",
            "-1",
            "--concurrency",
            "1",
        ),
        prof(
            "zero-concurrency",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "0",
        ),
        prof(
            "negative-concurrency",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "-1",
        ),
        prof(
            "zero-request-rate",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--request-rate",
            "0",
        ),
        prof(
            "negative-request-rate",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--request-rate",
            "-1",
        ),
        prof_pass(
            "both-concurrency-and-request-rate",
            "--endpoint-type",
            "chat",
            "--request-count",
            "2",
            "--concurrency",
            "1",
            "--request-rate",
            "1",
        ),
        prof_pass(
            "duration-and-request-count",
            "--endpoint-type",
            "chat",
            "--request-count",
            "2",
            "--benchmark-duration",
            "5",
        ),
        prof_pass(
            "bad-arrival-pattern-for-concurrency",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--arrival-pattern",
            "gamma",
        ),
        prof(
            "gamma-without-request-rate",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--arrival-pattern",
            "gamma",
            "--arrival-smoothness",
            "0.5",
        ),
        prof(
            "bad-arrival-smoothness-negative",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--request-rate",
            "1",
            "--arrival-pattern",
            "gamma",
            "--arrival-smoothness",
            "-0.1",
        ),
        prof_pass(
            "bad-arrival-smoothness-large",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--request-rate",
            "1",
            "--arrival-pattern",
            "gamma",
            "--arrival-smoothness",
            "999",
        ),
        prof(
            "bad-seq-dist-syntax",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--seq-dist",
            "not-a-dist",
        ),
        prof(
            "bad-extra-inputs",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--extra-inputs",
            "notkv",
        ),
        prof(
            "bad-header",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--header",
            "NoColonHeader",
        ),
        prof(
            "http2-transport-local-mock",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--transport",
            "http2",
        ),
        prof(
            "invalid-url-scheme",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--url",
            "ftp://127.0.0.1:36037",
        ),
        prof(
            "custom-endpoint-missing-leading-slash",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--custom-endpoint",
            "v1/chat/completions",
        ),
        prof(
            "template-endpoint-without-template",
            "--endpoint-type",
            "template",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--custom-endpoint",
            "/v1/custom-multimodal",
        ),
        prof_pass(
            "gpu-telemetry-and-no-gpu-telemetry",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--gpu-telemetry",
            f"{URL}/dcgm1/metrics",
        ),
        prof_pass(
            "server-metrics-and-no-server-metrics",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--server-metrics",
            f"{URL}/metrics",
            "--no-server-metrics",
        ),
        prof(
            "bad-server-metrics-format",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--server-metrics",
            f"{URL}/metrics",
            "--server-metrics-formats",
            "bogus",
        ),
        prof(
            "bad-export-level",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--export-level",
            "everything",
        ),
        prof(
            "negative-slice-duration",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--slice-duration",
            "-1",
        ),
        prof(
            "bad-model-selection-weighted-no-weights",
            "--endpoint-type",
            "chat",
            "--model",
            "m1,m2",
            "--model-selection-strategy",
            "weighted",
            "--request-count",
            "1",
            "--concurrency",
            "1",
        ),
        prof(
            "bad-url-strategy",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--url-strategy",
            "random",
        ),
        prof(
            "bad-connection-reuse-strategy",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--connection-reuse-strategy",
            "forever",
        ),
        prof(
            "warmup-negative",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--warmup-request-count",
            "-1",
        ),
        prof_pass(
            "warmup-prefill-fallback",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--streaming",
            "--prefill-concurrency",
            "1",
            "--warmup-request-count",
            "1",
        ),
        prof(
            "cancellation-rate-over-100",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--streaming",
            "--request-cancellation-rate",
            "101",
            "--request-cancellation-delay",
            "0",
        ),
        prof(
            "cancellation-negative-delay",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--streaming",
            "--request-cancellation-rate",
            "50",
            "--request-cancellation-delay",
            "-1",
        ),
        prof(
            "prefix-mutual-exclusion",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--num-prefix-prompts",
            "2",
            "--prefix-prompt-length",
            "8",
            "--shared-system-prompt-length",
            "4",
        ),
        prof(
            "random-pool-with-batch-size",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--input-file",
            str(random_pool),
            "--custom-dataset-type",
            "random-pool",
            "--batch-size",
            "2",
        ),
        # Mock-server edge cases should either pass or fail gracefully without traceback markers.
        prof_pass(
            "streaming-unsupported-chat-embeddings-downshift",
            "--endpoint-type",
            "chat-embeddings",
            "--custom-endpoint",
            "/v1/chat/embeddings",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--streaming",
            "--batch-size",
            "2",
        ),
        prof_pass(
            "video-generation-form-data-audio",
            "--endpoint-type",
            "video-generation",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--video-width",
            "32",
            "--video-height",
            "32",
            "--video-duration",
            "1",
            "--video-fps",
            "1",
            "--video-format",
            "mp4",
            "--request-content-type",
            "multipart/form-data",
            "--download-video-content",
            "--video-audio-sample-rate",
            "16000",
            "--video-audio-num-channels",
            "1",
            "--video-audio-codec",
            "aac",
            "--video-audio-depth",
            "16",
        ),
        prof_gpu_pass(
            "gpu-telemetry-dashboard-url",
            "--endpoint-type",
            "chat",
            "--request-count",
            "1",
            "--concurrency",
            "1",
            "--gpu-telemetry",
            "dashboard",
            f"{URL}/dcgm1/metrics",
        ),
        prof_pass(
            "multiple-models-round-robin",
            "--endpoint-type",
            "chat",
            "--model",
            "m1,m2",
            "--request-count",
            "2",
            "--concurrency",
            "1",
            "--model-selection-strategy",
            "round-robin",
        ),
        prof_pass(
            "multi-url-round-robin",
            "--endpoint-type",
            "chat",
            "--url",
            URL,
            "--request-count",
            "2",
            "--concurrency",
            "1",
            "--url-strategy",
            "round_robin",
        ),
        # Full non-Kubernetes happy-path gauntlet coverage ported from the temporary runner.
        cmd_pass("root-help", ["uv", "run", "aiperf", "--help"]),
        cmd_pass("version", ["uv", "run", "aiperf", "--version"]),
        cmd_pass("profile-help", ["uv", "run", "aiperf", "profile", "--help"]),
        cmd_pass("config-help", ["uv", "run", "aiperf", "config", "--help"]),
        cmd_pass(
            "config-init-help", ["uv", "run", "aiperf", "config", "init", "--help"]
        ),
        cmd_pass("plugins-help", ["uv", "run", "aiperf", "plugins", "--help"]),
        cmd_pass("plot-help", ["uv", "run", "aiperf", "plot", "--help"]),
        cmd_pass("synthesize-help", ["uv", "run", "aiperf", "synthesize", "--help"]),
        cmd_pass("validate-help", ["uv", "run", "aiperf", "validate", "--help"]),
        cmd_pass(
            "analyze-trace-help", ["uv", "run", "aiperf", "analyze-trace", "--help"]
        ),
        cmd_pass(
            "speed-bench-report-help",
            ["uv", "run", "aiperf", "speed-bench-report", "--help"],
        ),
        cmd_pass("plugins-default", ["uv", "run", "aiperf", "plugins"]),
        cmd_pass("plugins-all", ["uv", "run", "aiperf", "plugins", "--all"]),
        cmd_pass("plugins-validate", ["uv", "run", "aiperf", "plugins", "--validate"]),
        cmd_pass("plugins-category", ["uv", "run", "aiperf", "plugins", "endpoint"]),
        cmd_pass(
            "plugins-specific", ["uv", "run", "aiperf", "plugins", "endpoint", "chat"]
        ),
        cmd_pass(
            "config-init-list",
            ["uv", "run", "aiperf", "config", "init", "--list", "--verbose"],
        ),
        cmd_pass(
            "config-init-search",
            ["uv", "run", "aiperf", "config", "init", "--search", "goodput"],
        ),
        cmd_pass(
            "config-init-template",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "init",
                "--template",
                "minimal",
                "--model",
                "mock-model",
                "--url",
                URL,
                "--output",
                str(FIX / "init_minimal.yaml"),
            ],
        ),
        # `aiperf config generate/show/schema/diff` were retired; only
        # init/expand/validate remain. Verify the retired verbs fail cleanly.
        (
            "config-generate-yaml",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "generate",
                "--model",
                "mock-model",
                "--url",
                URL,
                "--endpoint-type",
                "chat",
                "--request-count",
                "1",
                "--tokenizer",
                "builtin",
                "--ui",
                "none",
                "--output",
                str(FIX / "generated.yaml"),
            ],
            60,
            "fail",
        ),
        (
            "config-generate-json",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "generate",
                "--model",
                "mock-model",
                "--url",
                URL,
                "--endpoint-type",
                "chat",
                "--request-count",
                "1",
                "--tokenizer",
                "builtin",
                "--ui",
                "none",
                "--format",
                "json",
            ],
            60,
            "fail",
        ),
        # `aiperf config validate` no longer accepts `--path`; it takes the
        # path as a positional argument. The legacy `--path` form is rejected.
        (
            "config-validate",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "validate",
                "--path",
                str(FIX / "generated.yaml"),
            ],
            60,
            "fail",
        ),
        (
            "config-show",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "show",
                "--path",
                str(FIX / "generated.yaml"),
                "--format",
                "json",
            ],
            60,
            "fail",
        ),
        (
            "config-schema",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "schema",
                "--output",
                str(FIX / "schema.json"),
            ],
            60,
            "fail",
        ),
        (
            "config-diff",
            [
                "uv",
                "run",
                "aiperf",
                "config",
                "diff",
                "--config1",
                str(FIX / "generated.yaml"),
                "--config2",
                str(FIX / "generated.yaml"),
                "--format",
                "json",
            ],
            60,
            "fail",
        ),
        # `profile --config` depends on the retired `config generate` step
        # above producing generated.yaml; with that gone the fixture file is
        # absent and aiperf reports a clean "Configuration file not found".
        (
            "profile-from-config",
            ["uv", "run", "aiperf", "profile", "--config", str(FIX / "generated.yaml")],
            180,
            "fail",
        ),
        cmd_pass(
            "profile-template-config",
            ["uv", "run", "aiperf", "profile", "--config", str(template_config)],
            180,
        ),
        profile_full("profile-chat", "--endpoint-type", "chat"),
        profile_full(
            "profile-chat-streaming-headers-extra-server-count",
            "--endpoint-type",
            "chat",
            "--streaming",
            "--use-server-token-count",
            "--header",
            "X-Test:gauntlet",
            "--extra-inputs",
            "temperature:0.1",
            "--api-key",
            "test-key",
            "--connection-reuse-strategy",
            "never",
        ),
        profile_full(
            "profile-chat-ready-transport",
            "--endpoint-type",
            "chat",
            "--transport",
            "http",
        ),
        profile_full(
            "profile-chat-ready-mode-interval",
            "--endpoint-type",
            "chat",
            "--wait-for-model-timeout",
            "5",
            "--wait-for-model-mode",
            "both",
            "--wait-for-model-interval",
            "1",
        ),
        profile_full(
            "profile-chat-sticky-sessions",
            "--endpoint-type",
            "chat",
            "--num-sessions",
            "2",
            "--conversation-turn-mean",
            "2",
            "--connection-reuse-strategy",
            "sticky-user-sessions",
        ),
        profile_full(
            "profile-multi-url",
            "--endpoint-type",
            "chat",
            "--url-strategy",
            "round_robin",
            urls=[URL, URL],
        ),
        profile_full(
            "profile-local-api-port",
            "--endpoint-type",
            "chat",
            "--api-host",
            "127.0.0.1",
            "--api-port",
            free_port(),
        ),
        profile_full(
            "profile-no-server-metrics",
            "--endpoint-type",
            "chat",
            server_metrics_disabled=True,
        ),
        profile_full(
            "profile-completions-streaming-legacy",
            "--endpoint-type",
            "completions",
            "--streaming",
            "--use-legacy-max-tokens",
        ),
        profile_full("profile-responses", "--endpoint-type", "responses"),
        profile_full(
            "profile-embeddings", "--endpoint-type", "embeddings", "--batch-size", "2"
        ),
        profile_full(
            "profile-chat-embeddings",
            "--endpoint-type",
            "chat-embeddings",
            "--custom-endpoint",
            "/v1/chat/embeddings",
            "--batch-size",
            "2",
        ),
        profile_full(
            "profile-nim-embeddings",
            "--endpoint-type",
            "nim-embeddings",
            "--batch-size",
            "2",
        ),
        profile_full(
            "profile-nim-rankings",
            "--endpoint-type",
            "nim-rankings",
            "--rankings-passages-mean",
            "2",
        ),
        profile_full(
            "profile-hf-tei-rankings",
            "--endpoint-type",
            "hf-tei-rankings",
            "--rankings-passages-mean",
            "2",
        ),
        profile_full(
            "profile-cohere-rankings",
            "--endpoint-type",
            "cohere-rankings",
            "--rankings-passages-mean",
            "2",
        ),
        profile_full(
            "profile-huggingface-generate", "--endpoint-type", "huggingface-generate"
        ),
        profile_full(
            "profile-huggingface-generate-streaming",
            "--endpoint-type",
            "huggingface-generate",
            "--streaming",
        ),
        profile_full("profile-image-generation", "--endpoint-type", "image-generation"),
        profile_full(
            "profile-video-generation",
            "--endpoint-type",
            "video-generation",
            "--video-width",
            "32",
            "--video-height",
            "32",
            "--video-duration",
            "1",
            "--video-fps",
            "1",
            "--video-format",
            "mp4",
            "--download-video-content",
        ),
        profile_full(
            "profile-video-generation-form-data-audio",
            "--endpoint-type",
            "video-generation",
            "--video-width",
            "32",
            "--video-height",
            "32",
            "--video-duration",
            "1",
            "--video-fps",
            "1",
            "--video-format",
            "mp4",
            "--request-content-type",
            "multipart/form-data",
            "--download-video-content",
            "--video-audio-sample-rate",
            "16000",
            "--video-audio-num-channels",
            "1",
            "--video-audio-codec",
            "aac",
            "--video-audio-depth",
            "16",
        ),
        profile_full(
            "profile-image-retrieval",
            "--endpoint-type",
            "image-retrieval",
            "--image-batch-size",
            "1",
            tokenizer=False,
        ),
        profile_full("profile-solido-rag", "--endpoint-type", "solido-rag"),
        profile_full(
            "profile-concurrency",
            "--endpoint-type",
            "chat",
            request_count="4",
            concurrency="2",
        ),
        profile_full(
            "profile-request-rate-constant",
            "--endpoint-type",
            "chat",
            "--request-rate",
            "2",
            "--arrival-pattern",
            "constant",
            request_count="4",
            concurrency=None,
        ),
        profile_full(
            "profile-request-rate-gamma",
            "--endpoint-type",
            "chat",
            "--request-rate",
            "2",
            "--arrival-pattern",
            "gamma",
            "--arrival-smoothness",
            "0.5",
            request_count="4",
            concurrency=None,
        ),
        profile_full(
            "profile-duration",
            "--endpoint-type",
            "chat",
            "--benchmark-duration",
            "5",
            "--benchmark-grace-period",
            "1",
        ),
        profile_full(
            "profile-warmup",
            "--endpoint-type",
            "chat",
            "--warmup-request-count",
            "1",
            "--warmup-concurrency",
            "1",
        ),
        profile_full(
            "profile-warmup-prefill-fallback",
            "--endpoint-type",
            "chat",
            "--streaming",
            "--prefill-concurrency",
            "1",
            "--warmup-request-count",
            "1",
        ),
        profile_full(
            "profile-cancellation",
            "--endpoint-type",
            "chat",
            "--streaming",
            "--request-cancellation-rate",
            "50",
            "--request-cancellation-delay",
            "0",
            request_count="8",
        ),
        profile_full(
            "profile-sweep-repeated",
            "--endpoint-type",
            "chat",
            "--num-profile-runs",
            "2",
            "--confidence-level",
            "0.9",
            "--parameter-sweep-mode",
            "repeated",
            "--parameter-sweep-cooldown-seconds",
            "0",
            request_count="2",
            concurrency="1,2",
            timeout=240,
        ),
        profile_full(
            "profile-sweep-independent",
            "--endpoint-type",
            "chat",
            "--parameter-sweep-mode",
            "independent",
            "--parameter-sweep-cooldown-seconds",
            "0",
            request_count="2",
            concurrency="1,2",
            timeout=240,
        ),
        profile_full(
            "profile-synthetic-seq-dist",
            "--endpoint-type",
            "chat",
            "--seq-dist",
            "16,8:50;32,16:50",
            "--random-seed",
            "42",
            "--no-set-consistent-seed",
        ),
        profile_full(
            "profile-prefix-pool",
            "--endpoint-type",
            "chat",
            "--num-prefix-prompts",
            "2",
            "--prefix-prompt-length",
            "8",
        ),
        profile_full(
            "profile-context-prompts",
            "--endpoint-type",
            "chat",
            "--shared-system-prompt-length",
            "4",
            "--user-context-prompt-length",
            "4",
        ),
        profile_full(
            "profile-multimodal-image",
            "--endpoint-type",
            "chat",
            "--image-batch-size",
            "1",
            "--image-width-mean",
            "32",
            "--image-height-mean",
            "32",
            "--image-format",
            "png",
        ),
        profile_full(
            "profile-multimodal-audio",
            "--endpoint-type",
            "chat",
            "--audio-batch-size",
            "1",
            "--audio-length-mean",
            "1",
            "--audio-format",
            "wav",
            "--audio-sample-rates",
            "16000",
            "--audio-num-channels",
            "1",
        ),
        profile_full(
            "profile-multimodal-video",
            "--endpoint-type",
            "chat",
            "--video-batch-size",
            "1",
            "--video-width",
            "32",
            "--video-height",
            "32",
            "--video-duration",
            "1",
            "--video-fps",
            "1",
            "--video-format",
            "mp4",
        ),
        profile_full(
            "profile-output-exports",
            "--endpoint-type",
            "chat",
            "--export-level",
            "raw",
            "--slice-duration",
            "1",
            "--export-http-trace",
            "--export-per-chunk-data",
            "--show-trace-timing",
            "--profile-export-prefix",
            "gauntlet",
        ),
        profile_full(
            "profile-export-file",
            "--endpoint-type",
            "chat",
            "--profile-export-file",
            str(ART / "custom-profile-export.json"),
        ),
        profile_full(
            "profile-server-metrics",
            "--endpoint-type",
            "chat",
            "--server-metrics",
            f"{URL}/metrics",
            f"{URL}/vllm/metrics",
            "--server-metrics-formats",
            "json",
            "csv",
        ),
        profile_full(
            "profile-gpu-telemetry",
            "--endpoint-type",
            "chat",
            "--gpu-telemetry",
            f"{URL}/dcgm1/metrics",
            gpu_disabled=False,
        ),
        profile_full(
            "profile-gpu-telemetry-dashboard",
            "--endpoint-type",
            "chat",
            "--gpu-telemetry",
            "dashboard",
            f"{URL}/dcgm1/metrics",
            gpu_disabled=False,
        ),
        profile_full(
            "profile-single-turn-dataset",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(single),
            "--custom-dataset-type",
            "single-turn",
            "--dataset-sampling-strategy",
            "sequential",
        ),
        profile_full(
            "profile-multi-turn-dataset",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(multi_turn),
            "--custom-dataset-type",
            "multi-turn",
            "--dataset-sampling-strategy",
            "sequential",
        ),
        profile_full(
            "profile-mooncake-fixed-schedule",
            "--endpoint-type",
            "chat",
            "--input-file",
            str(mooncake),
            "--custom-dataset-type",
            "mooncake-trace",
            "--fixed-schedule",
            "--fixed-schedule-auto-offset",
            "--fixed-schedule-end-offset",
            "25",
        ),
        profile_full(
            "profile-num-conversations",
            "--endpoint-type",
            "chat",
            "--num-conversations",
            "2",
            request_count=None,
        ),
        cmd_pass(
            "synthesize-agentic-code",
            [
                "uv",
                "run",
                "aiperf",
                "synthesize",
                "agentic-code",
                "--num-sessions",
                "2",
                "--output",
                str(FIX / "synth"),
                "--seed",
                "42",
                "--max-isl",
                "512",
                "--max-osl",
                "128",
            ],
            120,
        ),
        cmd_pass(
            "validate-mooncake-trace",
            [
                "uv",
                "run",
                "aiperf",
                "validate",
                "mooncake-trace",
                "--input",
                str(mooncake),
            ],
        ),
        cmd_pass(
            "analyze-trace",
            [
                "uv",
                "run",
                "aiperf",
                "analyze-trace",
                "--input-file",
                str(mooncake),
                "--block-size",
                "512",
                "--output-file",
                str(FIX / "trace_analysis.json"),
            ],
        ),
        cmd_pass(
            "plot-fixtures",
            [
                "uv",
                "run",
                "aiperf",
                "plot",
                "--paths",
                str(BASE / "tests/unit/plot/fixtures/qwen_concurrency1"),
                "--output",
                str(ART / "plot"),
                "--theme",
                "dark",
                "--verbose",
            ],
            120,
        ),
        cmd_pass(
            "speed-bench-report-table",
            [
                "uv",
                "run",
                "aiperf",
                "speed-bench-report",
                str(speed_root),
                "--format",
                "table",
                "--metric",
                "accept_rate",
            ],
        ),
        cmd_pass(
            "speed-bench-report-csv",
            [
                "uv",
                "run",
                "aiperf",
                "speed-bench-report",
                str(speed_root),
                "--format",
                "csv",
                "--metric",
                "throughput",
                "--output",
                str(ART / "speed_report.csv"),
            ],
        ),
    ]
    return [tuple_case(case) for case in cases]
