#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate attribution files from pip-licenses JSON output.

Normalizes license identifiers to SPDX IDs, validates them against an
allow/deny list, then writes an updated JSON (with SPDX IDs), a human-readable
markdown file, and a CSV summary for compliance tooling.

Usage:
    python3 tools/generate_python_attributions.py \\
        <input.json> <output.md> <output.csv> <licenses.toml>
"""

import csv
import json
import re
import sys
import tomllib
from pathlib import Path

_HEADER = """\
<!--
SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
-->

# Third-Party Software Attributions

This project uses the following third-party libraries. Each library is open-source and licensed under the terms indicated below.

This file is automatically generated. Please do not edit it directly.
"""

# Maps pip-licenses license strings (lowercased) to canonical SPDX identifiers.
# Unrecognised strings are left as-is so nothing is silently dropped.
_SPDX_MAP: dict[str, str] = {
    # MIT
    "mit": "MIT",
    "mit license": "MIT",
    "the mit license": "MIT",
    "the mit license (mit)": "MIT",
    "mit no attribution": "MIT-0",
    # Apache
    "apache software license": "Apache-2.0",
    "apache license 2.0": "Apache-2.0",
    "apache license, version 2.0": "Apache-2.0",
    "apache 2.0": "Apache-2.0",
    "apache 2.0 license": "Apache-2.0",
    "apache2": "Apache-2.0",
    "apache-2.0": "Apache-2.0",
    # BSD
    "bsd license": "BSD-3-Clause",
    "bsd": "BSD-3-Clause",
    "new bsd license": "BSD-3-Clause",
    "modified bsd license": "BSD-3-Clause",
    'bsd 3-clause "new" or "revised" license': "BSD-3-Clause",
    "bsd 3-clause license": "BSD-3-Clause",
    "3-clause bsd license": "BSD-3-Clause",
    "bsd-3-clause": "BSD-3-Clause",
    "simplified bsd": "BSD-2-Clause",
    'bsd 2-clause "simplified" license': "BSD-2-Clause",
    "bsd 2-clause license": "BSD-2-Clause",
    "bsd-2-clause": "BSD-2-Clause",
    # ISC
    "isc license (iscl)": "ISC",
    "isc license": "ISC",
    "isc": "ISC",
    # GPL
    "gnu general public license (gpl)": "GPL-2.0-or-later",
    "gnu general public license v2 (gplv2)": "GPL-2.0-only",
    "gnu general public license v2 or later (gplv2+)": "GPL-2.0-or-later",
    "gpl-2.0": "GPL-2.0-only",
    "gpl-2.0-only": "GPL-2.0-only",
    "gpl v2": "GPL-2.0-only",
    "gnu general public license v3 (gplv3)": "GPL-3.0-only",
    "gnu general public license v3 or later (gplv3+)": "GPL-3.0-or-later",
    "gpl-3.0": "GPL-3.0-only",
    "gpl-3.0-only": "GPL-3.0-only",
    "gpl v3": "GPL-3.0-only",
    # LGPL
    "gnu lesser general public license v2 (lgplv2)": "LGPL-2.0-only",
    "gnu lesser general public license v2 or later (lgplv2+)": "LGPL-2.0-or-later",
    "lgpl-2.0": "LGPL-2.0-only",
    "gnu lesser general public license v3 (lgplv3)": "LGPL-3.0-only",
    "gnu lesser general public license v3 or later (lgplv3+)": "LGPL-3.0-or-later",
    "lgpl-3.0": "LGPL-3.0-only",
    # AGPL
    "gnu affero general public license v3": "AGPL-3.0-only",
    "gnu affero general public license v3 or later (agplv3+)": "AGPL-3.0-or-later",
    "agpl-3.0": "AGPL-3.0-only",
    # Mozilla
    "mozilla public license 2.0 (mpl 2.0)": "MPL-2.0",
    "mozilla public license 2.0": "MPL-2.0",
    "mpl-2.0": "MPL-2.0",
    "mpl 2.0": "MPL-2.0",
    # Python
    "python software foundation license": "PSF-2.0",
    "psfl": "PSF-2.0",
    "python license (psfl)": "PSF-2.0",
    # Eclipse
    "eclipse public license 2.0 (epl-2.0)": "EPL-2.0",
    "eclipse public license 1.0 (epl-1.0)": "EPL-1.0",
    "epl-2.0": "EPL-2.0",
    "epl-1.0": "EPL-1.0",
    # Academic Free License
    "academic free license (afl)": "AFL-3.0",
    "afl-3.0": "AFL-3.0",
    # Other common
    "historical permission notice and disclaimer (hpnd)": "HPND",
    "hpnd": "HPND",
    "the unlicense (unlicense)": "Unlicense",
    "unlicense": "Unlicense",
    "creative commons zero v1.0 universal": "CC0-1.0",
    "cc0 1.0 universal (cc0 1.0) public domain dedication": "CC0-1.0",
    "cc0-1.0": "CC0-1.0",
    "artistic license": "Artistic-2.0",
    "artistic license 2.0": "Artistic-2.0",
    "zlib/libpng license": "Zlib",
    "zlib": "Zlib",
    "boost software license 1.0 (bsl-1.0)": "BSL-1.0",
    "bsl-1.0": "BSL-1.0",
    "european union public licence 1.2 (eupl 1.2)": "EUPL-1.2",
    "eupl-1.2": "EUPL-1.2",
    "common development and distribution license 1.0 (cddl-1.0)": "CDDL-1.0",
    "cddl-1.0": "CDDL-1.0",
}

# Classifier tokens that carry no license identity and should be dropped when
# splitting multi-classifier strings (e.g. "DFSG approved; MIT License").
_CLASSIFIER_NOISE: frozenset[str] = frozenset(
    {
        "dfsg approved",
        "osi approved",
        "public domain",
    }
)

# Splits a compound SPDX expression into individual identifiers.
# Handles AND/OR operators and parentheses, e.g.:
#   "MPL-2.0 AND (Apache-2.0 OR MIT)" → ["MPL-2.0", "Apache-2.0", "MIT"]
_SPDX_SPLIT = re.compile(r"\bAND\b|\bOR\b|\bWITH\b|[()]")


def _normalize_spdx(license_str: str) -> str:
    """Return the canonical SPDX identifier for a pip-licenses license string.

    Handles three failure modes from pip-licenses output:
    - License text bleeding into the field (multi-line or comment-prefixed)
    - Multiple semicolon-joined PyPI classifier values
    - Simple strings not yet in the map (returned unchanged)
    """
    raw = license_str.strip()

    # Detect license text bleeding into the License field: pip-licenses
    # sometimes puts the raw file content here for packages without clean
    # metadata. Extract the first meaningful line and try to normalize that.
    if "\n" in raw or raw.startswith("#"):
        for line in raw.splitlines():
            line = line.strip().lstrip("#").strip()
            if line:
                raw = line
                break

    # Handle multiple classifiers joined with ";" (PyPI trove classifier style).
    # Map each recognisable part to SPDX and join with " AND " (conservative —
    # treat all listed licenses as simultaneously applicable).
    if ";" in raw:
        parts = [p.strip() for p in raw.split(";")]
        normalized = [
            _SPDX_MAP.get(p.lower(), p)
            for p in parts
            if p.lower() not in _CLASSIFIER_NOISE
        ]
        return " AND ".join(normalized) if normalized else raw

    return _SPDX_MAP.get(raw.lower(), raw)


def _extract_spdx_ids(expression: str) -> list[str]:
    """Extract individual SPDX identifiers from a compound expression.

    Strips AND/OR/WITH operators and parentheses, returning only the
    identifiers themselves (e.g. ["MPL-2.0", "Apache-2.0", "MIT"]).
    """
    tokens = [t.strip() for t in _SPDX_SPLIT.split(expression)]
    return [t for t in tokens if t]


def _license_label(full_path: str) -> str:
    """Strip the absolute venv prefix from a license path, keeping the path
    relative to the dist-info directory (e.g. 'licenses/LICENSE')."""
    parts = Path(full_path).parts
    for i, part in enumerate(parts):
        if part.endswith(".dist-info"):
            return str(Path(*parts[i + 1 :]))
    return Path(full_path).name


def main() -> None:
    if len(sys.argv) != 5:
        print(
            f"Usage: {sys.argv[0]} <input.json> <output.md> <output.csv> <licenses.toml>",
            file=sys.stderr,
        )
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_md = Path(sys.argv[2])
    output_csv = Path(sys.argv[3])
    config_path = Path(sys.argv[4])

    with config_path.open("rb") as f:
        config = tomllib.load(f)

    allow: set[str] = set(config["licenses"]["allow"])
    deny: set[str] = set(config["licenses"]["deny"])
    # Build exception lookup keyed by (name, version) — python-typed entries only
    exceptions: dict[tuple[str, str], dict] = {
        (e["name"], e["version"]): e
        for e in config.get("exceptions", [])
        if e.get("type") == "python"
    }

    data = json.loads(input_path.read_text())

    # Normalize License field to SPDX IDs
    for pkg in data:
        pkg["License"] = _normalize_spdx(pkg.get("License", "UNKNOWN"))

    # Apply per-package exceptions: override License and optionally LicenseText
    for pkg in data:
        key = (pkg["Name"], pkg["Version"])
        if key in exceptions:
            exc = exceptions[key]
            pkg["License"] = exc["spdx"]
            if "license_text" in exc:
                pkg["LicenseText"] = exc["license_text"]

    # Write normalized JSON back so it can be used for compliance tooling
    input_path.write_text(json.dumps(data, indent=2))

    # Validate all packages against allow/deny lists
    failures: list[str] = []
    exception_keys = set(exceptions.keys())
    for pkg in data:
        key = (pkg["Name"], pkg["Version"])
        if key in exception_keys:
            continue
        license_str = pkg.get("License", "UNKNOWN")
        ids = _extract_spdx_ids(license_str)
        for spdx_id in ids:
            if spdx_id in deny:
                failures.append(
                    f"  DENIED   {pkg['Name']} ({pkg['Version']}): {spdx_id}"
                )
            elif spdx_id not in allow:
                failures.append(
                    f"  UNKNOWN  {pkg['Name']} ({pkg['Version']}): {spdx_id!r} not in allow list"
                )

    if failures:
        print("License validation failed:\n" + "\n".join(failures), file=sys.stderr)
        sys.exit(1)

    # Filter first-party: we don't attribute ourselves. Matches pyproject.toml
    # project.name. Update if the project is ever renamed.
    sorted_data = sorted(
        (pkg for pkg in data if pkg["Name"].lower() != "aiperf"),
        key=lambda x: x["Name"].lower(),
    )

    with output_md.open("w") as f:
        f.write(_HEADER)
        for pkg in sorted_data:
            f.write(f"\n## {pkg['Name']} ({pkg['Version']})\n")
            f.write("\n### Licenses\n")
            f.write(f"License: `{pkg.get('License', 'UNKNOWN')}`\n\n")
            text = pkg.get("LicenseText", "").strip()
            if text:
                label = _license_label(pkg.get("LicensePath", "")) or "LICENSE"
                f.write(f"  - `{label}`:\n```\n{text}\n```\n\n")
            url = pkg.get("URL", "")
            if url and url not in ("", "UNKNOWN"):
                f.write("### URLs\n")
                f.write(f"  - `Homepage`: {url}\n")
            f.write("\n")

    with output_csv.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["dependency_type", "name", "version", "spdx_license"])
        for pkg in sorted_data:
            writer.writerow(
                ["python", pkg["Name"], pkg["Version"], pkg.get("License", "UNKNOWN")]
            )


if __name__ == "__main__":
    main()
